version: "3.8"

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000        # user ID on the host
      - PGID=1000        # group ID on the host
      - TZ=Etc/UTC
      - USER=admin
      - PASS=password
    volumes:
      - ./data:/config          # Transmission settings.json stored here
      - ./data:/downloads    # where finished downloads go
      - ./data:/watch            # auto-load torrents placed here
    ports:
      - "9091:9091"     # Web UI
      - "51413:51413"   # Torrent port TCP
      - "51413:51413/udp"
    restart: unless-stopped
